api_endpoint: http://192.168.8.129:9090
api_key: YJ2-hA3-r3h-KDo
include_regex: "é¦™æ¸¯"
exclude_regex: "10(\\.0)?x|5(\\.0)?x|3(\\.0)x"
test_url: https://www.google.com
retrieve_interval: 3600 # æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡èŠ‚ç‚¹åˆ—è¡¨
current_interval: 300  # å¯¹å½“å‰èŠ‚ç‚¹æ¯5åˆ†é’Ÿæµ‹é€Ÿä¸€æ¬¡
best_interval: 1800 # å¯¹æ‰€æœ‰èŠ‚ç‚¹æ¯åŠå°æ—¶æµ‹é€Ÿä¸€æ¬¡ï¼Œé€‰å‡ºæœ€ä¼˜èŠ‚ç‚¹
test_times: 8 # å¤šæ¬¡æµ‹é€Ÿå–å¹³å‡å€¼
select_node: "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
latency_threshold: 250 # å»¶è¿Ÿé˜ˆå€¼ï¼Œå•ä½ms

