api_endpoint: http://192.168.10.2:9090
api_key: gbU-k7v-r9B-hUy
include_regex: "é¦™æ¸¯"
exclude_regex: "10(\\.0)?x|5(\\.0)?x|3(\\.0)x"
test_url: https://www.google.com
retrieve_interval: 600 # æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡èŠ‚ç‚¹åˆ—è¡¨
current_interval: 1  # å¯¹å½“å‰èŠ‚ç‚¹æ¯5åˆ†é’Ÿæµ‹é€Ÿä¸€æ¬¡
best_interval: 1 # å¯¹æ‰€æœ‰èŠ‚ç‚¹æ¯åŠå°æ—¶æµ‹é€Ÿä¸€æ¬¡ï¼Œé€‰å‡ºæœ€ä¼˜èŠ‚ç‚¹
test_times: 3 # æ¯æ¬¡æµ‹é€Ÿå–å¹³å‡å€¼
select_node: "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
